const placesData = [
  {
    name: 'Prashar Lake',
    state: 'Himachal Pradesh',
    region: 'North',
    description:
      'A stunning high-altitude lake nestled at 2,730 meters in the Dhauladhar range, famous for its floating island that changes position with the seasons. The ancient three-storied pagoda temple dedicated to Sage Prashar on its banks adds a mystical charm to the pristine blue waters surrounded by snow-capped peaks.',
    category: 'mountain',
    season: 'summer',
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    monthlyHighlights: [
      { month: 3, reason: 'Snow begins to melt revealing vibrant meadows around the lake' },
      { month: 5, reason: 'Clear skies offer stunning views of the Dhauladhar range' },
      { month: 10, reason: 'Post-monsoon clarity and golden autumn foliage on the trek' },
    ],
    crowdScore: 'low',
    crowdNote: 'Remains relatively untouched due to the moderate trek required to reach the lake.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 800, mid: 2000, luxury: 4500 },
    coordinates: { type: 'Point', coordinates: [77.1025, 31.7580] },
    altitude: '2,730 m',
    nearestCity: 'Mandi',
    distanceFromNearestCity: '49 km',
    highlights: [
      'Floating island in the lake',
      'Ancient pagoda-style Prashar Rishi Temple',
      'Panoramic Dhauladhar range views',
      'Camping under star-filled skies',
      'Moderate trek through pine forests',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?prashar-lake,india',
      detail: 'https://source.unsplash.com/800x600/?prashar-lake,travel',
      thumb: 'https://source.unsplash.com/400x300/?prashar-lake,india',
    },
    howToReach: {
      train: 'Nearest railway station is Joginder Nagar (55 km) on the narrow gauge line from Pathankot.',
      bus: 'HRTC buses run from Mandi to Baggi village, the trek base point.',
      road: 'Drive from Mandi via Katindhi to Baggi village, then a 7 km trek to the lake.',
    },
    rating: 4.6,
    reviewCount: 185,
  },
  {
    name: 'Ziro Valley',
    state: 'Arunachal Pradesh',
    region: 'Northeast',
    description:
      'A UNESCO World Heritage Site tentative list entry, Ziro Valley is the homeland of the Apatani tribe known for their unique facial tattoos and sustainable wet rice cultivation. The flat, pine-clad valley surrounded by low hills bursts with emerald rice paddies and hosts the iconic Ziro Music Festival every September.',
    category: 'village',
    season: 'all-year',
    bestMonths: [3, 4, 5, 9, 10, 11],
    monthlyHighlights: [
      { month: 4, reason: 'Rice planting season showcases the Apatani agricultural traditions' },
      { month: 9, reason: 'Ziro Music Festival draws indie music lovers from across India' },
      { month: 10, reason: 'Golden harvest season paints the valley in warm amber tones' },
    ],
    crowdScore: 'low',
    crowdNote: 'Remote location and Inner Line Permit requirement keeps crowds minimal year-round.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 1000, mid: 2500, luxury: 5000 },
    coordinates: { type: 'Point', coordinates: [93.8311, 27.5884] },
    altitude: '1,572 m',
    nearestCity: 'Itanagar',
    distanceFromNearestCity: '115 km',
    highlights: [
      'Apatani tribal village walks',
      'Ziro Music Festival in September',
      'Lush rice paddy terraces',
      'Talley Valley Wildlife Sanctuary',
      'Pine grove nature trails',
      'Traditional bamboo and cane crafts',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?ziro-valley,india',
      detail: 'https://source.unsplash.com/800x600/?ziro-valley,travel',
      thumb: 'https://source.unsplash.com/400x300/?ziro-valley,india',
    },
    howToReach: {
      train: 'Nearest railhead is Naharlagun (130 km), connected to Guwahati by Jan Shatabdi.',
      bus: 'State transport buses and shared Sumos run daily from Itanagar and Naharlagun.',
      road: 'NH 229 from Itanagar takes about 5 hours through scenic mountain roads.',
    },
    rating: 4.7,
    reviewCount: 220,
  },
  {
    name: 'Lonar Crater Lake',
    state: 'Maharashtra',
    region: 'West',
    description:
      'Formed by a meteorite impact around 50,000 years ago, Lonar is the only known hyper-velocity impact crater in basaltic rock anywhere on Earth. The saline and alkaline lake glows an otherworldly green and pink hue due to unique algae, with ancient temples dotting its rim and surrounding forests sheltering peacocks and gazelles.',
    category: 'heritage',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Pleasant winter weather ideal for crater rim hikes' },
      { month: 1, reason: 'Migratory flamingos sometimes visit the lake' },
      { month: 3, reason: 'Clear skies and wildflowers around the crater rim trails' },
    ],
    crowdScore: 'low',
    crowdNote: 'Despite its geological significance, Lonar sees very few tourists due to its remote location in Buldhana district.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 700, mid: 1800, luxury: 3500 },
    coordinates: { type: 'Point', coordinates: [76.5069, 19.9758] },
    nearestCity: 'Aurangabad',
    distanceFromNearestCity: '150 km',
    highlights: [
      'Meteorite impact crater exploration',
      'Ancient Daitya Sudan Temple on the rim',
      'Unique saline-alkaline lake ecology',
      'Kamalja Devi Temple',
      'Birdwatching at the lake shore',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?lonar-crater-lake,india',
      detail: 'https://source.unsplash.com/800x600/?lonar-crater-lake,travel',
      thumb: 'https://source.unsplash.com/400x300/?lonar-crater-lake,india',
    },
    howToReach: {
      train: 'Nearest major station is Jalna (80 km), well connected to Mumbai and Hyderabad.',
      bus: 'MSRTC buses run from Aurangabad and Buldhana to Lonar town.',
      road: 'NH 361 connects Lonar to Aurangabad (150 km, about 3.5 hours by car).',
    },
    rating: 4.3,
    reviewCount: 130,
  },
  {
    name: 'Majuli Island',
    state: 'Assam',
    region: 'Northeast',
    description:
      'The world\'s largest river island sits in the mighty Brahmaputra and is a living repository of Assamese Neo-Vaishnavite culture with its ancient satras (monasteries) preserving centuries-old dance, music, and mask-making traditions. Despite losing land to erosion each year, the island\'s lush wetlands support a rich ecosystem of migratory birds and rare river dolphins.',
    category: 'wildlife',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Raas Mahotsav festival featuring traditional Vaishnavite performances' },
      { month: 1, reason: 'Peak season for migratory birds from Siberia and Southeast Asia' },
      { month: 3, reason: 'Ali Ai Ligang spring festival of the Mising tribe' },
    ],
    crowdScore: 'rising',
    crowdNote: 'Growing recognition as a cultural and ecological treasure is steadily increasing visitor numbers.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 600, mid: 1500, luxury: 3000 },
    coordinates: { type: 'Point', coordinates: [94.2170, 26.9500] },
    nearestCity: 'Jorhat',
    distanceFromNearestCity: '20 km (plus ferry)',
    highlights: [
      'Ancient Vaishnavite satras and monasteries',
      'Traditional mask-making workshops',
      'Migratory bird watching at wetlands',
      'Cycling through rural Assamese villages',
      'Ferry ride across the Brahmaputra',
      'Mishing tribal stilt-house stays',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?majuli-island,india',
      detail: 'https://source.unsplash.com/800x600/?majuli-island,travel',
      thumb: 'https://source.unsplash.com/400x300/?majuli-island,india',
    },
    howToReach: {
      train: 'Nearest station is Jorhat Town (20 km to Nimati Ghat), connected to Guwahati.',
      bus: 'Buses run from Jorhat to Nimati Ghat, then a 1-hour public ferry to Majuli.',
      road: 'Drive to Nimati Ghat ferry point from Jorhat; private boats also available.',
    },
    rating: 4.5,
    reviewCount: 310,
  },
  {
    name: 'Chopta',
    state: 'Uttarakhand',
    region: 'North',
    description:
      'Known as the "Mini Switzerland of Uttarakhand," Chopta is a small meadow region that serves as the base for the iconic trek to Tungnath, the highest Shiva temple in the world, and the dramatic Chandrashila summit. The lush bugyals (alpine meadows) blanketed with wildflowers in summer transform into a pristine snow-covered wonderland during winter months.',
    category: 'mountain',
    season: 'all-year',
    bestMonths: [3, 4, 5, 6, 9, 10, 11, 12],
    monthlyHighlights: [
      { month: 5, reason: 'Rhododendron blooms carpet the meadows in vivid red and pink' },
      { month: 10, reason: 'Crystal-clear post-monsoon skies reveal the entire Garhwal Himalayan panorama' },
      { month: 12, reason: 'Fresh snowfall creates magical winter trekking conditions' },
    ],
    crowdScore: 'rising',
    crowdNote: 'Increasingly popular among weekend trekkers from Delhi and Dehradun, especially during holidays.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 900, mid: 2200, luxury: 5000 },
    coordinates: { type: 'Point', coordinates: [79.2190, 30.4400] },
    altitude: '2,680 m',
    nearestCity: 'Rudraprayag',
    distanceFromNearestCity: '40 km',
    highlights: [
      'Trek to Tungnath — world\'s highest Shiva temple',
      'Chandrashila summit sunrise views',
      'Alpine meadows with wildflowers',
      'Birdwatching for Himalayan monal',
      'Snow trekking in winter',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?chopta,india',
      detail: 'https://source.unsplash.com/800x600/?chopta,travel',
      thumb: 'https://source.unsplash.com/400x300/?chopta,india',
    },
    howToReach: {
      train: 'Nearest railway station is Rishikesh (202 km), connected to Delhi and Haridwar.',
      bus: 'Buses from Rishikesh and Rudraprayag run to Ukhimath, then shared jeeps to Chopta.',
      road: 'Drive via Rishikesh–Rudraprayag–Ukhimath; the road is well-maintained till Chopta.',
    },
    rating: 4.5,
    reviewCount: 420,
  },
  {
    name: 'Tirthan Valley',
    state: 'Himachal Pradesh',
    region: 'North',
    description:
      'A pristine valley carved by the Tirthan River that forms the buffer zone of the Great Himalayan National Park, a UNESCO World Heritage Site teeming with rare wildlife and alpine flora. Crystal-clear trout streams, dense oak and deodar forests, and warm Himachali homestays make it an ideal escape for those seeking solitude and adventure without the usual hill-station chaos.',
    category: 'mountain',
    season: 'all-year',
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    monthlyHighlights: [
      { month: 4, reason: 'Spring wildflowers and comfortable trekking temperatures' },
      { month: 6, reason: 'Trout fishing season in the crystal-clear Tirthan River' },
      { month: 10, reason: 'Autumn colors transform the valley into a painter\'s canvas' },
    ],
    crowdScore: 'low',
    crowdNote: 'Overshadowed by nearby Manali and Kasol, Tirthan remains peaceful even during peak season.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 800, mid: 2500, luxury: 6000 },
    coordinates: { type: 'Point', coordinates: [77.3500, 31.6380] },
    altitude: '1,600 m',
    nearestCity: 'Kullu',
    distanceFromNearestCity: '50 km',
    highlights: [
      'Great Himalayan National Park treks',
      'Trout fishing in the Tirthan River',
      'Serloskar Lake hike',
      'Traditional Himachali homestay experiences',
      'Birdwatching for Western Tragopan',
      'Waterfall rappelling at Chhoie waterfall',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?tirthan-valley,india',
      detail: 'https://source.unsplash.com/800x600/?tirthan-valley,travel',
      thumb: 'https://source.unsplash.com/400x300/?tirthan-valley,india',
    },
    howToReach: {
      train: 'Nearest broad-gauge station is Ambala (280 km), narrow gauge at Joginder Nagar.',
      bus: 'HRTC buses from Delhi and Chandigarh to Aut tunnel, then local bus to Banjar.',
      road: 'Take NH 21 to Aut, then a scenic 26 km diversion into the valley via Banjar.',
    },
    rating: 4.7,
    reviewCount: 275,
  },
  {
    name: 'Mechuka',
    state: 'Arunachal Pradesh',
    region: 'Northeast',
    description:
      'A remote valley town near the Indo-China border surrounded by snow-capped mountains and dense bamboo forests, Mechuka feels like a hidden Shangri-La accessible only by a winding mountain road. The 400-year-old Samten Yongcha Monastery and the Memba tribe\'s unique Tibetan-influenced culture give this valley an ethereal, timeless quality.',
    category: 'village',
    season: 'summer',
    bestMonths: [3, 4, 5, 9, 10, 11],
    monthlyHighlights: [
      { month: 4, reason: 'Clear skies and blooming rhododendrons throughout the valley' },
      { month: 10, reason: 'Mechuka Adventure Festival with river rafting and paragliding' },
      { month: 11, reason: 'Autumn foliage with spectacular views of snow-draped peaks' },
    ],
    crowdScore: 'low',
    crowdNote: 'Extremely remote with limited infrastructure, visited only by adventurous travelers willing to endure a long journey.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 900, mid: 2000, luxury: 4000 },
    coordinates: { type: 'Point', coordinates: [94.1397, 28.6200] },
    altitude: '1,829 m',
    nearestCity: 'Along',
    distanceFromNearestCity: '180 km',
    highlights: [
      'Samten Yongcha Monastery (400 years old)',
      'Siyom River valley treks',
      'Mechuka Adventure Festival',
      'Memba tribal culture and homestays',
      'Paragliding over the valley',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?mechuka,india',
      detail: 'https://source.unsplash.com/800x600/?mechuka,travel',
      thumb: 'https://source.unsplash.com/400x300/?mechuka,india',
    },
    howToReach: {
      train: 'Nearest railhead is Murkongselek (350 km), connected to Guwahati.',
      bus: 'Limited state transport from Along to Mechuka, often requiring an overnight halt.',
      road: 'Drive from Along (180 km, 8–10 hours) on a rough but scenic mountain road.',
    },
    rating: 4.6,
    reviewCount: 65,
  },
  {
    name: 'Gokarna',
    state: 'Karnataka',
    region: 'South',
    description:
      'Once a quiet temple town on the Konkan coast, Gokarna now draws travelers seeking the laid-back beach culture that Goa has slowly lost, with crescent-shaped coves accessible only by cliff trails or boat. The ancient Mahabaleshwara Temple anchors the town\'s spiritual identity while pristine beaches like Om Beach and Half Moon Beach offer surfing, yoga retreats, and beachside bonfires.',
    category: 'beach',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Perfect beach weather with minimal rainfall and warm seas' },
      { month: 1, reason: 'Peak season for surfing and beachside yoga retreats' },
      { month: 2, reason: 'Maha Shivaratri celebrations at Mahabaleshwara Temple' },
    ],
    crowdScore: 'popular',
    crowdNote: 'Growing fast as a Goa alternative; Om Beach and Kudle Beach get busy during winter holidays.',
    budgetLevel: 'mid',
    estimatedCostPerDay: { budget: 1000, mid: 3000, luxury: 7000 },
    coordinates: { type: 'Point', coordinates: [74.3188, 14.5479] },
    nearestCity: 'Karwar',
    distanceFromNearestCity: '60 km',
    highlights: [
      'Beach trek from Kudle to Half Moon Beach',
      'Surfing and paddleboarding at Om Beach',
      'Mahabaleshwara Temple visit',
      'Sunset at Paradise Beach',
      'Yoga and wellness retreats',
      'Fresh seafood shacks on the shore',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?gokarna,india',
      detail: 'https://source.unsplash.com/800x600/?gokarna,travel',
      thumb: 'https://source.unsplash.com/400x300/?gokarna,india',
    },
    howToReach: {
      train: 'Gokarna Road station (20 km) is on the Konkan Railway line from Mumbai to Mangalore.',
      bus: 'KSRTC and private buses run from Bangalore (480 km), Goa (150 km), and Mangalore (240 km).',
      road: 'NH 66 connects Gokarna to Goa and Mangalore; well-maintained coastal highway.',
    },
    rating: 4.4,
    reviewCount: 480,
  },
  {
    name: 'Rani ki Vav',
    state: 'Gujarat',
    region: 'West',
    description:
      'An intricately carved 11th-century stepwell in Patan, Rani ki Vav was built by Queen Udayamati as a memorial to her husband and is considered the finest example of subterranean water architecture in India. With over 800 ornate sculptures across seven gallery levels depicting Vishnu avatars, apsaras, and naginis, it earned UNESCO World Heritage status and a place on India\'s ₹100 currency note.',
    category: 'heritage',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Cool weather perfect for exploring the stepwell\'s seven levels' },
      { month: 1, reason: 'International Kite Festival in nearby Ahmedabad adds to the trip' },
      { month: 3, reason: 'Golden hour light illuminates the stepwell\'s intricate carvings beautifully' },
    ],
    crowdScore: 'rising',
    crowdNote: 'Visitor numbers have grown since UNESCO listing and appearance on the ₹100 note, but weekdays remain comfortable.',
    budgetLevel: 'mid',
    estimatedCostPerDay: { budget: 800, mid: 2500, luxury: 5500 },
    coordinates: { type: 'Point', coordinates: [72.1024, 23.8590] },
    nearestCity: 'Ahmedabad',
    distanceFromNearestCity: '130 km',
    highlights: [
      '800+ intricate stone sculptures',
      'UNESCO World Heritage Site',
      'Seven-level subterranean architecture',
      'Vishnu avatar carvings and apsara panels',
      'Nearby Patola silk weaving heritage',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?rani-ki-vav,india',
      detail: 'https://source.unsplash.com/800x600/?rani-ki-vav,travel',
      thumb: 'https://source.unsplash.com/400x300/?rani-ki-vav,india',
    },
    howToReach: {
      train: 'Patan station (5 km) has trains from Ahmedabad and Mehsana.',
      bus: 'Frequent GSRTC buses from Ahmedabad (130 km, 2.5 hours) and Mehsana (60 km).',
      road: 'Well-connected via NH 68 from Ahmedabad; excellent road conditions.',
    },
    rating: 4.5,
    reviewCount: 350,
  },
  {
    name: 'Spiti Valley',
    state: 'Himachal Pradesh',
    region: 'North',
    description:
      'A cold desert mountain valley perched between 3,800 and 4,500 meters, Spiti is one of the least populated regions in India with dramatic lunar landscapes, ancient Buddhist monasteries clinging to cliff faces, and villages frozen in time. The journey itself through treacherous mountain passes like Kunzum La is an unforgettable adventure, rewarding travelers with the thousand-year-old Key Monastery and the mummified monk of Gue village.',
    category: 'mountain',
    season: 'summer',
    bestMonths: [5, 6, 7, 8, 9],
    monthlyHighlights: [
      { month: 6, reason: 'Roads fully open after snow melt; ideal conditions for the Manali–Spiti circuit' },
      { month: 7, reason: 'Clear skies perfect for astrophotography in the pollution-free skies' },
      { month: 9, reason: 'Autumn light bathes monasteries and barley fields in golden hues' },
    ],
    crowdScore: 'rising',
    crowdNote: 'Social media popularity has increased visitors during July–August, but vast distances still keep it uncrowded.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 1200, mid: 3000, luxury: 6500 },
    coordinates: { type: 'Point', coordinates: [78.0350, 32.2460] },
    altitude: '3,800 m',
    nearestCity: 'Manali',
    distanceFromNearestCity: '200 km',
    highlights: [
      'Key Monastery — 1,000-year-old Buddhist gompa',
      'Chandratal Lake camping',
      'Dhankar Monastery perched on a cliff',
      'Highest post office in the world at Hikkim',
      'Fossil hunting at Langza village',
      'Stargazing in pristine dark skies',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?spiti-valley,india',
      detail: 'https://source.unsplash.com/800x600/?spiti-valley,travel',
      thumb: 'https://source.unsplash.com/400x300/?spiti-valley,india',
    },
    howToReach: {
      train: 'Nearest station is Joginder Nagar (290 km) or Shimla (412 km via road).',
      bus: 'HRTC runs a daily bus from Manali to Kaza (summer only) and Shimla to Kaza via Kinnaur.',
      road: 'Two routes: Manali–Rohtang–Kunzum La (seasonal) or Shimla–Kinnaur–Kaza (longer but scenic).',
    },
    rating: 4.8,
    reviewCount: 390,
  },
  {
    name: 'Bhimlat Falls',
    state: 'Rajasthan',
    region: 'West',
    description:
      'Hidden in the rugged Vindhyan hills near Bundi, Bhimlat is a thundering 60-meter waterfall that transforms an arid Rajasthani landscape into a lush green gorge during and after the monsoon. The remote approach through a forested ravine past ancient cenotaphs makes the discovery of this powerful cascade feel like stumbling upon a secret oasis in the desert state.',
    category: 'heritage',
    season: 'monsoon',
    bestMonths: [7, 8, 9, 10],
    monthlyHighlights: [
      { month: 8, reason: 'Peak monsoon flow creates a spectacular 60-meter cascade' },
      { month: 9, reason: 'Surrounding ravines turn emerald green with monsoon vegetation' },
      { month: 10, reason: 'Water flow remains strong while trails start to dry up for easier access' },
    ],
    crowdScore: 'low',
    crowdNote: 'Almost unknown outside Bundi locals; you may have the entire waterfall to yourself.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 600, mid: 1500, luxury: 3000 },
    coordinates: { type: 'Point', coordinates: [75.5760, 25.3700] },
    nearestCity: 'Bundi',
    distanceFromNearestCity: '35 km',
    highlights: [
      '60-meter waterfall in arid Rajasthan',
      'Lush monsoon gorge scenery',
      'Ancient cenotaphs along the trail',
      'Bundi\'s stepwells and Taragarh Fort nearby',
      'Natural swimming pools below the falls',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?bhimlat-falls,india',
      detail: 'https://source.unsplash.com/800x600/?bhimlat-falls,travel',
      thumb: 'https://source.unsplash.com/400x300/?bhimlat-falls,india',
    },
    howToReach: {
      train: 'Nearest station is Bundi (35 km), connected to Kota junction and Jaipur.',
      bus: 'Local buses from Bundi town towards Mangrol; ask for Bhimlat diversion.',
      road: 'Drive from Bundi via Mangrol road; last 5 km is a rough track to the falls.',
    },
    rating: 4.2,
    reviewCount: 55,
  },
  {
    name: 'Dholavira',
    state: 'Gujarat',
    region: 'West',
    description:
      'One of the largest and most prominent archaeological sites of the Indus Valley Civilisation, Dholavira sits on Khadir island in the vast white salt desert of the Rann of Kutch. The remarkably well-preserved ruins reveal a sophisticated 5,000-year-old city with advanced water harvesting systems, a grand citadel, and the world\'s earliest known signboard, earning UNESCO World Heritage status in 2021.',
    category: 'heritage',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Rann Utsav festival begins nearby, making it easy to combine trips' },
      { month: 1, reason: 'Cool desert temperatures ideal for exploring the excavation site' },
      { month: 2, reason: 'Full moon nights illuminate the white Rann surrounding the site' },
    ],
    crowdScore: 'low',
    crowdNote: 'Despite UNESCO status, the extreme remoteness in the Rann keeps visitor numbers very low.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 700, mid: 1800, luxury: 3500 },
    coordinates: { type: 'Point', coordinates: [70.2133, 23.8871] },
    nearestCity: 'Bhuj',
    distanceFromNearestCity: '250 km',
    highlights: [
      'UNESCO World Heritage Indus Valley ruins',
      'Ancient water harvesting reservoir system',
      'World\'s earliest known signboard',
      'Fossil park near the site',
      'White Rann salt desert landscape',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?dholavira,india',
      detail: 'https://source.unsplash.com/800x600/?dholavira,travel',
      thumb: 'https://source.unsplash.com/400x300/?dholavira,india',
    },
    howToReach: {
      train: 'Nearest station is Bhachau (200 km), on the Ahmedabad–Bhuj mainline.',
      bus: 'Limited GSRTC buses from Bhuj and Bhachau; private vehicles recommended.',
      road: 'Drive from Bhuj via Bhachau and Rapar through the flat Rann landscape (250 km, 5 hours).',
    },
    rating: 4.3,
    reviewCount: 95,
  },
  {
    name: 'Sandakphu',
    state: 'West Bengal',
    region: 'East',
    description:
      'At 3,636 meters, Sandakphu is the highest peak in West Bengal and the only place in India from where you can see four of the five tallest peaks in the world — Everest, Kangchenjunga, Lhotse, and Makalu — in a single breathtaking panorama. The trek through rhododendron forests passes through quaint mountain villages straddling the India–Nepal border, with the dramatic "Sleeping Buddha" silhouette of the Kangchenjunga range as the ultimate reward.',
    category: 'mountain',
    season: 'winter',
    bestMonths: [3, 4, 5, 10, 11, 12],
    monthlyHighlights: [
      { month: 4, reason: 'Rhododendron blooms paint the trail in brilliant red and pink' },
      { month: 10, reason: 'Crystal-clear post-monsoon visibility of the four highest peaks' },
      { month: 12, reason: 'Snow-dusted trails and dramatic Sleeping Buddha sunrise views' },
    ],
    crowdScore: 'low',
    crowdNote: 'Moderate difficulty trek and remote location in Singalila National Park limits crowds.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 1000, mid: 2500, luxury: 5000 },
    coordinates: { type: 'Point', coordinates: [88.0003, 27.1050] },
    altitude: '3,636 m',
    nearestCity: 'Siliguri',
    distanceFromNearestCity: '100 km',
    highlights: [
      'Views of Everest, Kangchenjunga, Lhotse, and Makalu',
      'Sleeping Buddha panorama at sunrise',
      'Rhododendron forest trek',
      'Singalila National Park wildlife',
      'India–Nepal border villages',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?sandakphu,india',
      detail: 'https://source.unsplash.com/800x600/?sandakphu,travel',
      thumb: 'https://source.unsplash.com/400x300/?sandakphu,india',
    },
    howToReach: {
      train: 'New Jalpaiguri (NJP) station (95 km to Manebhanjan trek base), connected to Kolkata and Delhi.',
      bus: 'Shared jeeps from Siliguri/Darjeeling to Manebhanjan, the starting point of the trek.',
      road: 'Drive to Manebhanjan (28 km from Darjeeling), then trek or take a Land Rover to the summit.',
    },
    rating: 4.6,
    reviewCount: 210,
  },
  {
    name: 'Munsiyari',
    state: 'Uttarakhand',
    region: 'North',
    description:
      'A remote frontier town perched at 2,298 meters in the Kumaon Himalayas, Munsiyari offers jaw-dropping views of the Panchachuli massif — five snow-capped peaks resembling the five hearths of the Pandavas from the Mahabharata. The town serves as the gateway to the Milam Glacier trek and the ancient Indo-Tibet trade route, with dense forests of rhododendron and birch sheltering Himalayan black bears and musk deer.',
    category: 'mountain',
    season: 'summer',
    bestMonths: [4, 5, 6, 9, 10, 11],
    monthlyHighlights: [
      { month: 5, reason: 'Spectacular rhododendron blooms with Panchachuli peaks as backdrop' },
      { month: 9, reason: 'Post-monsoon clarity ideal for the Milam Glacier trek' },
      { month: 10, reason: 'Autumn colors and snow-dusted Panchachuli massif views' },
    ],
    crowdScore: 'low',
    crowdNote: 'The long and winding road from Almora deters casual tourists, keeping Munsiyari peacefully quiet.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 800, mid: 2000, luxury: 4500 },
    coordinates: { type: 'Point', coordinates: [80.2379, 30.0669] },
    altitude: '2,298 m',
    nearestCity: 'Pithoragarh',
    distanceFromNearestCity: '90 km',
    highlights: [
      'Panchachuli massif panoramic views',
      'Milam Glacier trek base camp',
      'Khaliya Top alpine meadow trek',
      'Birthi Falls waterfall visit',
      'Tribal Heritage Museum',
      'Rhododendron and birch forest walks',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?munsiyari,india',
      detail: 'https://source.unsplash.com/800x600/?munsiyari,travel',
      thumb: 'https://source.unsplash.com/400x300/?munsiyari,india',
    },
    howToReach: {
      train: 'Nearest station is Kathgodam (295 km), connected to Delhi by overnight train.',
      bus: 'KMOU buses run from Almora and Pithoragarh; the journey takes 8–10 hours from Kathgodam.',
      road: 'Drive from Kathgodam via Almora–Bageshwar–Thal; a scenic but long mountain drive.',
    },
    rating: 4.5,
    reviewCount: 155,
  },
  {
    name: 'Hampi (outskirts)',
    state: 'Karnataka',
    region: 'South',
    description:
      'While the main Hampi ruins draw crowds, the lesser-known outskirts across the Tungabhadra River reveal sprawling boulder-strewn landscapes dotted with forgotten temples, ancient irrigation canals, and quiet banana plantations where you can explore without another tourist in sight. Areas like Anegundi — considered the mythological Kishkindha from the Ramayana — offer rock climbing, coracle rides, and sunset views from Anjaneya Hill.',
    category: 'heritage',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Hampi Utsav festival with cultural performances and processions' },
      { month: 1, reason: 'Cool, dry weather perfect for exploring the boulder landscapes' },
      { month: 3, reason: 'Fewer tourists than peak season; golden light on the ruins' },
    ],
    crowdScore: 'popular',
    crowdNote: 'Main Hampi is heavily visited, but the outskirts across the river remain blissfully uncrowded.',
    budgetLevel: 'mid',
    estimatedCostPerDay: { budget: 800, mid: 2500, luxury: 6000 },
    coordinates: { type: 'Point', coordinates: [76.4600, 15.3550] },
    nearestCity: 'Hospet',
    distanceFromNearestCity: '13 km',
    highlights: [
      'Anegundi village and mythological Kishkindha',
      'Rock climbing on ancient boulders',
      'Coracle rides on the Tungabhadra River',
      'Sunset from Anjaneya Hill (Hanuman birthplace)',
      'Hidden temples and ancient irrigation canals',
      'Cycling through banana plantations',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?hampi-outskirts,india',
      detail: 'https://source.unsplash.com/800x600/?hampi-outskirts,travel',
      thumb: 'https://source.unsplash.com/400x300/?hampi-outskirts,india',
    },
    howToReach: {
      train: 'Hospet Junction (13 km) is well-connected to Bangalore, Goa, and Hyderabad.',
      bus: 'Frequent KSRTC buses from Bangalore (350 km, 7 hours) and overnight from Goa.',
      road: 'NH 67 connects Hospet to major cities; auto-rickshaws ferry tourists from Hospet to Hampi.',
    },
    rating: 4.7,
    reviewCount: 450,
  },
  {
    name: 'Khajjiar',
    state: 'Himachal Pradesh',
    region: 'North',
    description:
      'Often called the "Mini Switzerland of India," Khajjiar is a small plateau with a saucer-shaped meadow surrounded by towering deodar cedars and a tiny lake at its center, all framed by distant snow peaks. The 12th-century Khajji Nag Temple dedicated to the serpent god adds cultural depth, while paragliding, zorbing, and horse rides across the green expanse make it a delightful family destination.',
    category: 'mountain',
    season: 'all-year',
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    monthlyHighlights: [
      { month: 5, reason: 'Lush green meadows at their most vibrant with clear Himalayan views' },
      { month: 9, reason: 'Post-monsoon freshness and fewer crowds than summer peak' },
      { month: 12, reason: 'Snowfall transforms the meadow into a winter wonderland' },
    ],
    crowdScore: 'rising',
    crowdNote: 'Weekend traffic from Dalhousie has increased, but midweek visits remain serene.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 900, mid: 2500, luxury: 5500 },
    coordinates: { type: 'Point', coordinates: [76.0534, 32.5413] },
    altitude: '1,951 m',
    nearestCity: 'Dalhousie',
    distanceFromNearestCity: '22 km',
    highlights: [
      'Saucer-shaped meadow with lake',
      'Paragliding over the green plateau',
      '12th-century Khajji Nag Temple',
      'Deodar cedar forest walks',
      'Horse riding across the meadows',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?khajjiar,india',
      detail: 'https://source.unsplash.com/800x600/?khajjiar,travel',
      thumb: 'https://source.unsplash.com/400x300/?khajjiar,india',
    },
    howToReach: {
      train: 'Nearest station is Pathankot (120 km), connected to Delhi and Amritsar.',
      bus: 'HRTC buses from Dalhousie (22 km) and Chamba; also from Pathankot via Dalhousie.',
      road: 'Drive from Dalhousie on a scenic winding road through deodar forests (45 minutes).',
    },
    rating: 4.3,
    reviewCount: 380,
  },
  {
    name: 'Dzukou Valley',
    state: 'Nagaland',
    region: 'Northeast',
    description:
      'Perched at 2,452 meters on the Nagaland–Manipur border, Dzukou Valley is a vast undulating meadow that erupts in a carpet of rare Dzukou Lilies found nowhere else on Earth during the July–September blooming season. The valley\'s dramatic mist-shrouded ridges, bamboo groves, and pristine streams make it one of the most beautiful and untouched trekking destinations in all of Northeast India.',
    category: 'wildlife',
    season: 'monsoon',
    bestMonths: [6, 7, 8, 9, 10, 11],
    monthlyHighlights: [
      { month: 7, reason: 'Rare Dzukou Lily blooms carpet the valley floor in white and pink' },
      { month: 9, reason: 'Lush green meadows with occasional mist creating ethereal scenery' },
      { month: 11, reason: 'Golden autumn foliage on the ridge trails with clear mountain views' },
    ],
    crowdScore: 'low',
    crowdNote: 'Protected area status and the trek-only access ensures very few visitors at any time.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 700, mid: 1800, luxury: 3500 },
    coordinates: { type: 'Point', coordinates: [94.1056, 25.5540] },
    altitude: '2,452 m',
    nearestCity: 'Kohima',
    distanceFromNearestCity: '30 km',
    highlights: [
      'Rare Dzukou Lily blooms (Jul–Sep)',
      'Undulating meadows and misty ridgelines',
      'Bamboo grove camping',
      'Pristine mountain streams',
      'Trek from Viswema or Jakhama village',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?dzukou-valley,india',
      detail: 'https://source.unsplash.com/800x600/?dzukou-valley,travel',
      thumb: 'https://source.unsplash.com/400x300/?dzukou-valley,india',
    },
    howToReach: {
      train: 'Nearest railhead is Dimapur (74 km from Kohima), on the Lumding–Dimapur line.',
      bus: 'Buses from Dimapur to Kohima (74 km), then local transport to Viswema trek base.',
      road: 'Drive to Viswema village (20 km south of Kohima), then a 5-hour trek to the valley.',
    },
    rating: 4.7,
    reviewCount: 120,
  },
  {
    name: 'Gandikota',
    state: 'Andhra Pradesh',
    region: 'South',
    description:
      'Dubbed the "Grand Canyon of India," Gandikota features a dramatic gorge carved by the Pennar River through rust-red Erramala sandstone cliffs, crowned by a crumbling 13th-century fort with ancient temples and a granary within its walls. The sheer drop from the fort ramparts into the canyon below, especially at sunrise, creates a landscape so surreal that most visitors struggle to believe it exists in southern India.',
    category: 'heritage',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Cool temperatures and dramatic morning mist filling the canyon' },
      { month: 1, reason: 'Best visibility for photography of the gorge and Pennar River' },
      { month: 2, reason: 'Wildflowers on the canyon rim with comfortable camping weather' },
    ],
    crowdScore: 'low',
    crowdNote: 'Still relatively unknown despite its spectacular scenery; camping by the gorge feels completely private.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 600, mid: 1500, luxury: 3000 },
    coordinates: { type: 'Point', coordinates: [78.2840, 15.1725] },
    nearestCity: 'Kurnool',
    distanceFromNearestCity: '77 km',
    highlights: [
      'Pennar River gorge — India\'s Grand Canyon',
      '13th-century Gandikota Fort ruins',
      'Sunrise over the canyon rim',
      'Madhavarayaswamy Temple inside the fort',
      'Camping beside the gorge',
      'Kayaking on the Pennar River',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?gandikota,india',
      detail: 'https://source.unsplash.com/800x600/?gandikota,travel',
      thumb: 'https://source.unsplash.com/400x300/?gandikota,india',
    },
    howToReach: {
      train: 'Nearest station is Jammalamadugu (15 km) or Muddanuru on the Guntakal–Kurnool line.',
      bus: 'APSRTC buses from Kurnool (77 km) and Proddatur to Jammalamadugu; local auto to Gandikota.',
      road: 'Drive from Bangalore (320 km) via Anantapur or from Hyderabad (380 km) via Kurnool.',
    },
    rating: 4.4,
    reviewCount: 175,
  },
  {
    name: 'Bhedaghat',
    state: 'Madhya Pradesh',
    region: 'Central',
    description:
      'Home to the awe-inspiring Marble Rocks — towering 30-meter white marble cliffs that line the Narmada River for 8 kilometers — Bhedaghat offers one of India\'s most surreal boat rides, especially under moonlight when the marble glows ethereally. The nearby Dhuandhar Falls, where the Narmada thunders through a narrow gorge creating a permanent mist, and the ancient Chausath Yogini Temple on a hilltop complete this geological and cultural wonder.',
    category: 'heritage',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Full moon boat rides between the glowing marble cliffs' },
      { month: 1, reason: 'Cool, mist-free days perfect for Dhuandhar Falls photography' },
      { month: 3, reason: 'Spring greenery along the marble gorge before the heat sets in' },
    ],
    crowdScore: 'low',
    crowdNote: 'Domestic tourists visit on weekends, but the 8-km gorge ensures you can always find solitude.',
    budgetLevel: 'budget',
    estimatedCostPerDay: { budget: 600, mid: 1500, luxury: 3500 },
    coordinates: { type: 'Point', coordinates: [79.7980, 23.1080] },
    nearestCity: 'Jabalpur',
    distanceFromNearestCity: '25 km',
    highlights: [
      'Marble Rocks moonlight boat ride',
      'Dhuandhar Falls on the Narmada River',
      'Chausath Yogini Temple (10th century)',
      'Cable car ride over the gorge',
      'Rock climbing on marble cliffs',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?bhedaghat,india',
      detail: 'https://source.unsplash.com/800x600/?bhedaghat,travel',
      thumb: 'https://source.unsplash.com/400x300/?bhedaghat,india',
    },
    howToReach: {
      train: 'Jabalpur Junction (25 km) is a major railway hub connected to Delhi, Mumbai, and Chennai.',
      bus: 'Frequent local buses and auto-rickshaws from Jabalpur city to Bhedaghat.',
      road: 'Well-connected via NH 44 to Jabalpur; the short drive to Bhedaghat is on a paved road.',
    },
    rating: 4.3,
    reviewCount: 290,
  },
  {
    name: 'Thalassery',
    state: 'Kerala',
    region: 'South',
    description:
      'A historic port town on the Malabar Coast where the British built one of their earliest forts in Kerala, Thalassery is the birthplace of the Indian circus tradition and the home of the iconic Thalassery biryani made with fragrant kaima rice. Muzhappilangad Drive-in Beach — Asia\'s longest drive-in beach — stretches for 4 kilometers, while the town\'s crumbling colonial warehouses and vibrant spice markets evoke its rich trading past.',
    category: 'beach',
    season: 'winter',
    bestMonths: [10, 11, 12, 1, 2, 3],
    monthlyHighlights: [
      { month: 11, reason: 'Calm seas and perfect weather for the drive-in beach experience' },
      { month: 12, reason: 'Christmas and New Year festivities in this historically Christian-influenced town' },
      { month: 2, reason: 'Thalassery Biryani food festivals and local cultural events' },
    ],
    crowdScore: 'low',
    crowdNote: 'Overshadowed by Varkala and Kovalam, Thalassery receives mostly domestic day-trippers.',
    budgetLevel: 'mid',
    estimatedCostPerDay: { budget: 800, mid: 2500, luxury: 5500 },
    coordinates: { type: 'Point', coordinates: [75.4910, 11.7480] },
    nearestCity: 'Kannur',
    distanceFromNearestCity: '22 km',
    highlights: [
      'Muzhappilangad Drive-in Beach (4 km)',
      'Thalassery Fort (1708 British era)',
      'Authentic Thalassery biryani trail',
      'Spice market and colonial warehouse district',
      'Dharmadam Island viewpoint',
      'Indian circus heritage museum',
    ],
    imageUrls: {
      hero: 'https://source.unsplash.com/800x600/?thalassery,india',
      detail: 'https://source.unsplash.com/800x600/?thalassery,travel',
      thumb: 'https://source.unsplash.com/400x300/?thalassery,india',
    },
    howToReach: {
      train: 'Thalassery railway station is on the Mangalore–Shoranur Konkan Railway line.',
      bus: 'KSRTC buses from Kozhikode (70 km) and Kannur (22 km) run frequently.',
      road: 'Located on NH 66 between Kannur and Kozhikode; excellent coastal highway.',
    },
    rating: 4.1,
    reviewCount: 160,
  },
];

module.exports = placesData;
